name: meu_app_financas
description: "A new Flutter project."
publish_to: 'none' # Remova esta linha se quiser publicar no pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  # Ícones padrão do iOS
  cupertino_icons: ^1.0.8

  # Comunicação com API REST
  http: ^1.4.0

  # Formatação de datas e números
  intl: ^0.20.2

  # Tipografia do Google
  google_fonts: ^6.3.0

  # ✅ Notificações locais atualizadas (corrige bugs)
  flutter_local_notifications: ^19.4.0

  # ✅ Suporte a fuso horário para notificações agendadas
  timezone: ^0.10.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Boas práticas de linting
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  # ✅ Imagens e fontes personalizadas (habilite se necessário)
  # assets:
  #   - assets/images/

  # fonts:
  #   - family: MinhaFonte
  #     fonts:
  #       - asset: fonts/MinhaFonte-Regular.ttf
